Repository osmosis-labs/osmosis-frontend, pull requests merged in 2022-10, with the labels that each got.

#864 Add ext osmo gauge to pool 806
  packages/web/config/feature-flag.ts
Labels: pool/asset

#873 Add teritori asset on Osmosis frontend
  packages/web/config/chain-infos.ts
  packages/web/config/ibc-assets.ts
  packages/web/config/price.ts
  packages/web/public/tokens/utori.png
  packages/web/public/tokens/utori.svg
Labels: pool/asset

#878 Use testnet historical data (Imperator) API on testnet
  packages/stores/src/queries-external/index.ts
  packages/stores/src/queries-external/pool-fees/index.ts
  packages/stores/src/queries-external/store.ts
  packages/stores/types/queries-external/index.d.ts
  packages/stores/types/queries-external/pool-fees/index.d.ts
  packages/stores/types/queries-external/store.d.ts
  packages/web/pages/pools/index.tsx
  packages/web/stores/root.ts
Labels: testnet 🦺

#881 Fix tori chain-infos
  packages/web/config/chain-infos.ts
Labels: pool/asset

#884 Fix stJUNO
  packages/web/config/chain-infos.ts
  packages/web/config/feature-flag.ts
  packages/web/config/ibc-assets.ts
  packages/web/config/price.ts
Labels: pool/asset

#876 update external incentives gauges for Stargaze
  packages/web/config/feature-flag.ts
Labels: pool/asset

#882 Update tori picture
  packages/web/config/chain-infos.ts
Labels: pool/asset

#879 chore: Add updated CHEQ gauges
  packages/web/config/feature-flag.ts
Labels: pool/asset

#885 Add WETH Integrated Axelar Transfer
  packages/stores/src/bridge-history/index.ts
  packages/stores/types/bridge-history/index.d.ts
  packages/web/config/ibc-assets.ts
  packages/web/integrations/axelar/index.ts
  packages/web/integrations/axelar/source-chain-config.ts
  packages/web/integrations/axelar/transfer.tsx
  packages/web/integrations/axelar/types.ts
  packages/web/stores/root.ts
Labels: pool/asset

#900 Define Sif price using local pools
  packages/web/config/chain-infos.ts
  packages/web/config/price.ts
Labels: pool/asset

#905 Add gauge for teritori pool 816
  packages/web/config/feature-flag.ts
Labels: pool/asset

#906 Add MUSE
  packages/web/config/chain-infos.ts
  packages/web/config/ibc-assets.ts
  packages/web/public/tokens/muse.svg
Labels: pool/asset

#903 Update gauge for likecoin pool 553 and 555
  packages/web/config/feature-flag.ts
Labels: pool/asset

#889 Move axl Transfer Fee Definition
  packages/stores/src/bridge-history/index.ts
  packages/stores/types/bridge-history/index.d.ts
  packages/web/config/chain-infos.ts
  packages/web/config/feature-flag.ts
  packages/web/config/ibc-assets.ts
  packages/web/config/price.ts
  packages/web/integrations/axelar/hooks/use-deposit-address.ts
  packages/web/integrations/axelar/index.ts
  packages/web/integrations/axelar/source-chain-config.ts
  packages/web/integrations/axelar/transfer.tsx
  packages/web/integrations/axelar/types.ts
  packages/web/public/tokens/utori.png
  packages/web/public/tokens/utori.svg
  packages/web/stores/root.ts
Labels: bug

#911 stATOM/ATOM pool 803 gauges
  packages/web/config/feature-flag.ts
Labels: pool/asset

#907 Add lambda to frontend
  packages/web/config/chain-infos.ts
  packages/web/config/ibc-assets.ts
  packages/web/config/price.ts
  packages/web/public/tokens/lambda.png
Labels: pool/asset

#914 Update EVMOS externals gauge
  packages/web/config/feature-flag.ts
Labels: pool/asset

#915 Update lambda price pool id
  packages/web/config/ibc-assets.ts
  packages/web/config/price.ts
Labels: pool/asset

#921 Added FUND and Unification
  packages/web/config/chain-infos.ts
  packages/web/config/ibc-assets.ts
  packages/web/config/price.ts
  packages/web/public/tokens/fund.png
Labels: pool/asset

#918 Add Gravity Externals
  packages/web/config/feature-flag.ts
Labels: pool/asset

#929 add new 810 gauge
  packages/web/config/feature-flag.ts
Labels: pool/asset

#930 Add lambda external incentives gauges
  packages/web/config/feature-flag.ts
Labels: pool/asset

#933 fix price pool
  packages/web/config/feature-flag.ts
  packages/web/config/price.ts
Labels: pool/asset

#940 Update feature-flag.ts
  packages/web/config/feature-flag.ts
Labels: pool/asset

#942 add stOSMO (ibc asset, pool price and gauge)
  packages/web/config/chain-infos.ts
  packages/web/config/feature-flag.ts
  packages/web/config/ibc-assets.ts
  packages/web/config/price.ts
Labels: pool/asset

#941 Add IST
  packages/web/config/ibc-assets.ts
Labels: pool/asset
