Repository osmosis-labs/osmosis-frontend, pull requests merged in 2022-03, with the labels that each got.

#290 Allow users to specify custom withdraw address
  src/dialogs/Transfer.tsx
  src/hooks/account/useCustomBech32Address.ts
Labels: enhancement, pre-refactor

#300 Change custom withdraw warning from tooltip -> textbox
  src/config.ts
  src/dialogs/Transfer.tsx
  src/pages/assets/AssetBalancesList.tsx
Labels: pre-refactor

#293 Refactor pool detail page (- pool actions)
  packages/math/package.json
  packages/pools/package.json
  packages/stores/package.json
  packages/stores/src/queries/pool-incentives/incentivized-pools.ts
  packages/stores/src/queries/pool-share/index.ts
  packages/stores/src/queries/pools/pools.ts
  packages/stores/src/queries/store.ts
  packages/web/components/assets/catalyst-icon.tsx
  packages/web/components/cards/incentivized-pool.tsx
  packages/web/components/cards/index.tsx
  packages/web/components/cards/my-pool.tsx
  packages/web/components/cards/pool-card.tsx
  packages/web/components/cards/pool-catalyst.tsx
  packages/web/components/cards/pool-gauge-bonus.tsx
  packages/web/components/cards/pool-gauge.tsx
  packages/web/components/overview/index.tsx
  packages/web/components/overview/overview-label-value.tsx
  packages/web/components/overview/types.ts
  packages/web/components/types.ts
  packages/web/components/utils.ts
  packages/web/config.ts
  packages/web/package.json
  packages/web/pages/pool/[id].tsx
  packages/web/public/icons/superfluid-osmo.svg
  packages/web/public/images/bubbles.svg
  packages/web/public/images/osmosis-guy-in-lab.png
  packages/web/stores/root.tsx
  packages/web/tailwind.config.js
  yarn.lock
Labels: refactor

#320 Updated coinGeckoID for Cerberus
  src/config.ts
Labels: pool/asset
