Repository osmosis-labs/osmosis-frontend, pull requests merged in 2022-04, with the labels that each got.

#314 Add Pool 638 to Trade router
  src/stores/root.ts
Labels: pool/asset

#334 Update STARS gauges
  src/config.ts
Labels: pool/asset

#324 Pool detail: manage liquidity dialog
  packages/stores/src/index.ts
  packages/stores/src/tx/ibc/ibc-transfer.ts
  packages/stores/src/tx/index.ts
  packages/stores/src/ui-config/amount-config.ts
  packages/stores/src/ui-config/fake-fee-config.ts
  packages/stores/src/ui-config/index.ts
  packages/stores/src/ui-config/manage-liquidity/add-liquidity.ts
  packages/stores/src/ui-config/manage-liquidity/base.ts
  packages/stores/src/ui-config/manage-liquidity/index.ts
  packages/stores/src/ui-config/manage-liquidity/remove-liquidity.ts
  packages/web/components/assets/catalyst-icon.tsx
  packages/web/components/assets/index.tsx
  packages/web/components/assets/pool-assets-icon.tsx
  packages/web/components/assets/rate-ring.tsx
  packages/web/components/assets/token.tsx
  packages/web/components/assets/types.ts
  packages/web/components/buttons/button.tsx
  packages/web/components/cards/pool-card.tsx
  packages/web/components/complex/pool/add-liquidity.tsx
  packages/web/components/complex/pool/remove-liquidity.tsx
  packages/web/components/control/checkbox.tsx
  packages/web/components/control/index.ts
  packages/web/components/control/pool-token-select.tsx
  packages/web/components/control/slider.tsx
  packages/web/components/control/tab-box.tsx
  packages/web/components/control/token-select.tsx
  packages/web/components/table/index.tsx
  packages/web/components/tooltip/index.ts
  packages/web/components/tooltip/info.tsx
  packages/web/components/tooltip/types.ts
  packages/web/components/trade-clipboard.tsx
  packages/web/components/utils.ts
  packages/web/modals/base.tsx
  packages/web/modals/manage-liquidity.tsx
  packages/web/package.json
  packages/web/pages/pool/[id].tsx
  yarn.lock
Labels: refactor

#327 Pool Detail: Bond LP tokens modal
  packages/web/modals/lock-tokens.tsx
  packages/web/pages/pool/[id].tsx
Labels: refactor

#336 add bitsong gauges
  src/config.ts
Labels: pool/asset

#344 Add UMEE External Incentives
  src/config.ts
Labels: pool/asset

#358 Puneet/newExternal incentives for 648, pstake/osmo
  src/config.ts
Labels: pool/asset

#386 Add Pool 669 $RAC External Incentives (OSMOS/RAC)
  src/config.ts
Labels: pool/asset

#376 Frontier - Add fet
  public/assets/tokens/fet.png
  public/assets/tokens/mobx.png
  src/config.ts
  src/stores/root.ts
Labels: pool/asset

#387 Add external incentives for Grav USDC pools
  src/config.ts
Labels: pool/asset

#390 Frontier - add Axelar pools
  src/config.ts
  src/stores/root.ts
Labels: pool/asset

#339 Pools Page: Create Pool dialog
  packages/stores/src/ui-config/create-pool.ts
  packages/stores/src/ui-config/index.ts
  packages/web/components/alert/info.tsx
  packages/web/components/chart/generate-series.ts
  packages/web/components/chart/gradients.ts
  packages/web/components/chart/index.ts
  packages/web/components/chart/pie-chart.tsx
  packages/web/components/complex/pool/add-liquidity.tsx
  packages/web/components/complex/pool/create/index.ts
  packages/web/components/complex/pool/create/step-base.tsx
  packages/web/components/complex/pool/create/step1-set-ratios.tsx
  packages/web/components/complex/pool/create/step2-add-liquidity.tsx
  packages/web/components/complex/pool/create/step3-confirm.tsx
  packages/web/components/complex/pool/create/types.ts
  packages/web/components/control/checkbox.tsx
  packages/web/components/control/token-select.tsx
  packages/web/components/input/input-box.tsx
  packages/web/components/trade-clipboard.tsx
  packages/web/hooks/index.ts
  packages/web/modals/create-pool.tsx
  packages/web/modals/ibc-transfer.tsx
  packages/web/modals/lock-tokens.tsx
  packages/web/package.json
  packages/web/pages/pool/[id].tsx
  packages/web/pages/pools/index.tsx
  packages/web/public/icons/add.svg
  packages/web/styles/globals.css
  yarn.lock
Labels: refactor

#342 Add superfluid
  packages/stores/.eslintignore
  packages/stores/src/account/index.ts
  packages/stores/src/account/msg/proto/generated/codecimpl.d.ts
  packages/stores/src/account/msg/proto/generated/codecimpl.js
  packages/stores/src/account/types.ts
  packages/stores/src/queries/index.ts
  packages/stores/src/queries/lockup/index.ts
  packages/stores/src/queries/lockup/synthetic.ts
  packages/stores/src/queries/lockup/types.ts
  packages/stores/src/queries/store.ts
  packages/stores/src/queries/superfluid-pools/asset-multiplier.ts
  packages/stores/src/queries/superfluid-pools/delegations.ts
  packages/stores/src/queries/superfluid-pools/index.ts
  packages/stores/src/queries/superfluid-pools/osmo-equivalent.ts
  packages/stores/src/queries/superfluid-pools/params.ts
  packages/stores/src/queries/superfluid-pools/pools.ts
  packages/stores/src/queries/superfluid-pools/types.ts
  packages/stores/src/queries/superfluid-pools/undelegations.ts
  packages/web/components/cards/pool-gauge.tsx
  packages/web/components/table/cells/index.ts
  packages/web/components/table/cells/types.ts
  packages/web/components/table/cells/validator-info.tsx
  packages/web/components/table/index.tsx
  packages/web/hooks/data/data-sorter.ts
  packages/web/hooks/data/use-sorted-data.ts
  packages/web/modals/index.tsx
  packages/web/modals/lock-tokens.tsx
  packages/web/modals/superfluid-validator.tsx
  packages/web/pages/assets/index.tsx
  packages/web/pages/pool/[id].tsx
  packages/web/pages/pools/index.tsx
  packages/web/public/icons/profile.svg
  packages/web/tailwind.config.js
Labels: refactor

#402 Saage testnet pool asset
  src/config.ts
Labels: pool/asset

#391 adding imversed testnet assets and pools to osmosis testnet frontend
  public/assets/tokens/imv.png
  src/config.ts
  src/stores/root.ts
Labels: pool/asset

#408 fix: change prefix for Axelar tokens
  src/config.ts
Labels: pool/asset

#406 Frontier - Add assetmantle
  public/assets/tokens/mntl.png
  src/config.ts
  src/stores/root.ts
Labels: pool/asset

#409 Update VDL incentive gauge-ids
  src/config.ts
Labels: pool/asset

#415 Akash v0.16.0
  src/config.ts
Labels: pool/asset

#432 Fr upd gamm3 ext
  src/config.ts
Labels: pool/asset

#431 Update GAMM 3 External incentives
  src/config.ts
Labels: pool/asset

#398 Limit swap amount
  src/pages/main/components/TokenAmountInput.tsx
Labels: bug, pre-refactor

#400 Frontier - Add HASH
  public/assets/tokens/hash.png
  public/assets/tokens/hash.svg
  src/config.ts
  src/stores/root.ts
Labels: pool/asset

#433 Update axelar URLs
  src/config.ts
Labels: pool/asset

#430 Remove dupe grav b embed
  src/config.ts
Labels: pool/asset

#436 Frontier - Updated Provenance Coingecko id
  src/config.ts
Labels: pool/asset
