Repository osmosis-labs/osmosis-frontend, pull requests merged in 2022-11, with the labels that each got.

#945 Add wbnb
  packages/web/config/chain-infos.ts
  packages/web/config/ibc-assets.ts
  packages/web/integrations/axelar/source-chain-config.ts
  packages/web/integrations/ethereum/metamask.ts
  packages/web/public/tokens/wbnb.svg
Labels: pool/asset

#944 added fund external incentives gauges + linting
  packages/web/config/feature-flag.ts
Labels: pool/asset

#948 Update LAMB/OSMO pool 14days gauge
  packages/web/config/feature-flag.ts
Labels: pool/asset

#963 add gauge for Rebus pool 813
  packages/web/config/feature-flag.ts
Labels: pool/asset

#967 Add IST price and Gauges
  packages/web/config/chain-infos.ts
  packages/web/config/feature-flag.ts
Labels: pool/asset

#964 update to new gauges for seJUNO, SEASY pools
  packages/web/config/feature-flag.ts
Labels: pool/asset

#969 update pool 817 gauge id
  packages/web/config/feature-flag.ts
Labels: pool/asset

#972 Add IST price
  packages/web/config/price.ts
Labels: pool/asset

#824 Enable Osmosis chain configuration overwrite
  packages/web/.env
  packages/web/README.md
  packages/web/config/chain-infos.ts
  packages/web/config/price.ts
  packages/web/stores/root.ts
Labels: testnet 🦺, developer-qol 💻

#986 Remove ROAWN's verified status
  packages/web/config/ibc-assets.ts
Labels: pool/asset

#999 WBNB.axl to Main site
  packages/web/config/ibc-assets.ts
Labels: pool/asset

#977 Fix Axl Network Selection
  packages/web/config/ibc-assets.ts
  packages/web/integrations/axelar/source-chain-config.ts
  packages/web/integrations/axelar/transfer.tsx
  packages/web/integrations/axelar/types.ts
  packages/web/integrations/axelar/utils.ts
  packages/web/integrations/bridge-info.ts
  packages/web/modals/transfer-asset-select.tsx
Labels: design 🎨

#1012 Calculate prices with pool weights
  packages/web/config/chain-infos.ts
  packages/web/config/price.ts
Labels: enhancement

#1013 Add Traditional Chinese translation
  packages/web/localizations/dayjs-locale-zh-tw.js
  packages/web/localizations/zh-tw.json
  packages/web/stores/user-settings/language.tsx
Labels: 🌎 localization

#1010 Fix bond duration
  packages/stores/src/queries/lockup/types.ts
  packages/stores/src/queries/pool-incentives/lockable-durations.ts
  packages/stores/src/queries/pool-share/index.ts
  packages/stores/src/ui-config/manage-liquidity/bond-liquidity.ts
  packages/stores/types/queries/lockup/types.d.ts
  packages/stores/types/queries/pool-incentives/lockable-durations.d.ts
  packages/stores/types/queries/pool-share/index.d.ts
  packages/stores/types/ui-config/manage-liquidity/bond-liquidity.d.ts
  packages/web/components/assets/catalyst-icon.tsx
  packages/web/components/assets/pool-assets-icon.tsx
  packages/web/components/cards/asset-card.tsx
  packages/web/components/cards/bond-card.tsx
  packages/web/components/complex/pool/create/step2-add-liquidity.tsx
  packages/web/components/control/token-select.tsx
  packages/web/hooks/ui-config/use-lock-token-config.ts
  packages/web/modals/lock-tokens.tsx
  packages/web/modals/token-select.tsx
  packages/web/pages/pool/[id].tsx
Labels: bug

#1020 Revert to CoinGecko Prices
  packages/web/config/chain-infos.ts
  packages/web/config/price.ts
Labels: performance 💨

#1026 Switch to CoinGecko IDs--no pool spot prices
  packages/web/config/chain-infos.ts
  packages/web/config/price.ts
Labels: performance 💨

#1032 Minor Prices Fixes
  packages/web/config/chain-infos.ts
  packages/web/config/price.ts
Labels: pool/asset

#1033 Bug fixes: Console Errors and Speed
  packages/web/config/chain-infos.ts
  packages/web/public/tokens/alter.svg
  packages/web/public/tokens/butt.svg
  packages/web/public/tokens/shd.svg
  packages/web/public/tokens/sienna.svg
  packages/web/public/tokens/stkd-scrt.svg
Labels: performance 💨

#1039 Update Chihuahua Chain Suggest Fees
  packages/web/config/chain-infos.ts
Labels: pool/asset

#956 Add ALTER, BUT, SHD, SIENNA & stkd-SCRT (Secret SNIP-20 tokens)
  packages/web/config/ibc-assets.ts
Labels: pool/asset

#1041 Replace FUND token logo with Circular logo
  packages/web/public/tokens/fund.png
Labels: pool/asset

#1040 Change CRBRUS to unstable, unverified
  packages/web/config/ibc-assets.ts
Labels: pool/asset

#1048 Make NETA, BOOT unverified
  packages/web/config/ibc-assets.ts
Labels: pool/asset

#1060 Update WETH Logo to SVG
  packages/web/config/chain-infos.ts
  packages/web/public/tokens/weth.svg
Labels: pool/asset

#1064 Update Osmo/Lamb pool gauge id
  packages/web/config/feature-flag.ts
Labels: pool/asset

#1067 add stSTARS / STARS gauge
  packages/web/config/feature-flag.ts
Labels: pool/asset

#1072 Re-enable bJuno
  packages/web/config/ibc-assets.ts
Labels: pool/asset

#1076 Pool Detail: Fix bond duration cards
  packages/stores/src/ui-config/manage-liquidity/bond-liquidity.ts
  packages/stores/types/ui-config/manage-liquidity/bond-liquidity.d.ts
  packages/web/components/cards/bond-card.tsx
  packages/web/modals/lock-tokens.tsx
  packages/web/pages/pool/[id].tsx
Labels: bug
