Repository osmosis-labs/osmosis-frontend, pull requests merged in 2023-03, with the labels that each got.

#1347 Swap tool fixes
  packages/web/components/drawers/token-select-drawer.tsx
  packages/web/components/trade-clipboard/index.tsx
  packages/web/modals/token-select.tsx
Labels: bug

#1365 Update MEME image
  packages/web/public/tokens/meme.png
Labels: pool/asset

#1203 Redesign pools table
  packages/stores/package.json
  packages/stores/src/queries-external/filtered-pools/filtered-pools.ts
  packages/web/.eslintrc.json
  packages/web/components/assets/icon.tsx
  packages/web/components/assets/pool-assets-name.tsx
  packages/web/components/chart/sparkline.tsx
  packages/web/components/complex/all-pools-table-set.tsx
  packages/web/components/complex/all-pools-table.tsx
  packages/web/components/complex/compact-pool-table-display.tsx
  packages/web/components/complex/external-incentivized-pools-table-set.tsx
  packages/web/components/complex/index.ts
  packages/web/components/complex/paginated-table.tsx
  packages/web/components/complex/pool/create/step3-confirm.tsx
  packages/web/components/control/language-select.tsx
  packages/web/components/control/menu-dropdown.tsx
  packages/web/components/control/select-menu.tsx
  packages/web/components/drawers/drawer.tsx
  packages/web/components/input/search-box.tsx
  packages/web/components/navbar/index.tsx
  packages/web/components/overview/pools.tsx
  packages/web/components/table/assets-table.tsx
  packages/web/components/table/cells/pool-quick-actions.tsx
  packages/web/components/table/index.tsx
  packages/web/components/trade-clipboard/index.tsx
  packages/web/hooks/data/use-filtered-data.ts
  packages/web/hooks/data/use-paginated-data.ts
  packages/web/hooks/data/use-sorted-data.ts
  packages/web/hooks/data/use-user-processed-data.ts
  packages/web/hooks/use-on-screen.ts
  packages/web/hooks/user-settings/use-hide-dust-filter.ts
  packages/web/integrations/ethereum/metamask-utils.ts
  packages/web/integrations/ethereum/metamask.ts
  packages/web/integrations/ethereum/queries/index.ts
  packages/web/localizations/en.json
  packages/web/modals/transfer-asset-select.tsx
  packages/web/package.json
  packages/web/pages/assets/index.tsx
  packages/web/pages/pool/[id].tsx
  packages/web/pages/pools/index.tsx
  packages/web/public/icons/arrow-right-wosmongton-100.svg
  packages/web/public/icons/sprite.svg
  packages/web/styles/globals.css
  yarn.lock
Labels: design 🎨

#1375 add $LDON info
  packages/web/config/chain-infos.ts
  packages/web/public/tokens/ft347B1612A2B7659913679CF6CD45B8B130C50A00.png
Labels: pool/asset

#1367 Add new CMDX logo
  packages/web/public/tokens/cmdx.png
Labels: pool/asset

#1382 Move FTM to Main
  packages/web/config/ibc-assets.ts
Labels: pool/asset

#1376 Add qATOM
  packages/web/config/chain-infos.ts
  packages/web/config/ibc-assets.ts
  packages/web/config/price.ts
  packages/web/public/tokens/qatom.svg
Labels: pool/asset

#1385 changes to add qREGEN
  packages/web/config/chain-infos.ts
  packages/web/config/ibc-assets.ts
  packages/web/config/price.ts
  packages/web/public/tokens/qregen.svg
Labels: pool/asset

#1387 Move CMST to Main
  packages/web/config/ibc-assets.ts
Labels: pool/asset

#1397 Update ETH logo with SVG
  packages/web/config/chain-infos.ts
  packages/web/public/tokens/eth-white.svg
  packages/web/public/tokens/eth.png
Labels: pool/asset

#1404 Add QCK
  packages/web/config/ibc-assets.ts
  packages/web/config/price.ts
Labels: pool/asset

#1406 Optimize BOOT img
  lunc.svg
  packages/web/config/chain-infos.ts
  packages/web/public/tokens/boot.png
  packages/web/public/tokens/boot.svg
Labels: pool/asset

#1411 Optimize RAW image
  packages/web/config/chain-infos.ts
  packages/web/public/tokens/raw.png
  packages/web/public/tokens/raw.svg
Labels: pool/asset

#1410 Optimize CANTO Image
  packages/web/config/chain-infos.ts
  packages/web/public/tokens/canto.png
  packages/web/public/tokens/canto.svg
Labels: pool/asset

#1416 Optimize NOM Image
  packages/web/config/chain-infos.ts
  packages/web/public/tokens/nom.png
  packages/web/public/tokens/nom.svg
Labels: pool/asset

#1417 Optimize LAMB Image
  packages/web/config/chain-infos.ts
  packages/web/public/tokens/lambda.png
  packages/web/public/tokens/lambda.svg
Labels: pool/asset

#1414 Update HASH Image
  packages/web/config/chain-infos.ts
  packages/web/public/tokens/hash.svg
  packages/web/public/tokens/prov.svg
Labels: pool/asset

#1413 Optimize HOPERS Image
  packages/web/config/chain-infos.ts
  packages/web/public/tokens/hopers.png
  packages/web/public/tokens/hopers.svg
Labels: pool/asset

#1408 Optimize KAVA, USDX Images
  packages/web/config/chain-infos.ts
  packages/web/public/tokens/kava.png
  packages/web/public/tokens/kava.svg
  packages/web/public/tokens/usdx.png
  packages/web/public/tokens/usdx.svg
Labels: pool/asset

#1407 Optimize arUSD, CNTO Images
  packages/web/config/chain-infos.ts
  packages/web/public/tokens/arusd.png
  packages/web/public/tokens/arusd.svg
  packages/web/public/tokens/cnto.png
  packages/web/public/tokens/cnto.svg
Labels: pool/asset

#1419 Optimize CRBRUS Image
  packages/web/config/chain-infos.ts
  packages/web/public/tokens/crbrus.png
  packages/web/public/tokens/crbrus.svg
Labels: pool/asset

#1402 Add ARKH
  packages/web/config/chain-infos.ts
  packages/web/config/ibc-assets.ts
  packages/web/config/price.ts
  packages/web/public/tokens/arkh.svg
Labels: pool/asset

#1426 Update ARKH Image
  packages/web/public/tokens/arkh.svg
Labels: pool/asset

#1433 Optimize CHEQ Image
  packages/web/public/tokens/cheq.svg
Labels: pool/asset

#1432 Optimize UMEE Image
  packages/web/config/chain-infos.ts
  packages/web/public/tokens/umee.png
  packages/web/public/tokens/umee.svg
Labels: pool/asset

#1431 Optimize Gravity Bridge Images
  packages/web/config/chain-infos.ts
  packages/web/public/tokens/dai.grv.svg
  packages/web/public/tokens/gdai.png
  packages/web/public/tokens/grav.svg
  packages/web/public/tokens/gusdc.png
  packages/web/public/tokens/gusdt.png
  packages/web/public/tokens/gwbtc.png
  packages/web/public/tokens/gweth.png
  packages/web/public/tokens/usdc.grv.svg
  packages/web/public/tokens/usdt.grv.svg
  packages/web/public/tokens/usdt.svg
  packages/web/public/tokens/wbtc.grv.svg
  packages/web/public/tokens/weth.grv.svg
Labels: pool/asset

#1430 Optimize FUND Image
  packages/web/config/chain-infos.ts
  packages/web/public/tokens/fund.png
  packages/web/public/tokens/fund.svg
Labels: pool/asset

#1436 Restore Bostrom BOOT IBC Transfer
  packages/web/config/ibc-assets.ts
Labels: pool/asset

#1439 Update non-ETH USDC Logos
  packages/web/config/chain-infos.ts
  packages/web/public/tokens/avalanche.usdc.svg
  packages/web/public/tokens/polygon.usdc.svg
Labels: pool/asset

#1429 Add qOSMO
  packages/web/config/chain-infos.ts
  packages/web/config/ibc-assets.ts
  packages/web/config/price.ts
  packages/web/public/tokens/qosmo.svg
Labels: pool/asset

#1435 Update IXO Chain Id
  packages/web/config/chain-infos.ts
  packages/web/config/ibc-assets.ts
Labels: pool/asset

#1427 feat: Add Observable Pools with Metrics
  packages/stores/src/chain.ts
  packages/stores/src/derived-data/index.ts
  packages/stores/src/derived-data/pool/bonding.ts
  packages/stores/src/derived-data/pools/index.ts
  packages/stores/src/derived-data/pools/metrics.ts
  packages/stores/src/derived-data/store.ts
  packages/stores/src/index.ts
  packages/web/components/alert/tx-event-toast.ts
  packages/web/components/assets/icon.tsx
  packages/web/components/assets/pool-assets-icon.tsx
  packages/web/components/complex/all-pools-table.tsx
  packages/web/components/complex/paginated-table.tsx
  packages/web/components/navbar-osmo-price.tsx
  packages/web/components/table/cells/pool-quick-actions.tsx
  packages/web/components/trade-clipboard/trade-route.tsx
  packages/web/config/chain-infos.ts
  packages/web/config/utils.ts
  packages/web/public/icons/sprite.svg
  packages/web/stores/assets/index.ts
  packages/web/stores/assets/types.ts
  packages/web/stores/root.ts
Labels: performance 💨

#1441 Publish Stage
  .eslintrc.base.js
  package.json
  packages/stores/src/chain.ts
  packages/stores/src/derived-data/index.ts
  packages/stores/src/derived-data/pool/bonding.ts
  packages/stores/src/derived-data/pools/index.ts
  packages/stores/src/derived-data/pools/metrics.ts
  packages/stores/src/derived-data/store.ts
  packages/stores/src/index.ts
  packages/web/components/alert/tx-event-toast.ts
  packages/web/components/assets/icon.tsx
  packages/web/components/assets/pool-assets-icon.tsx
  packages/web/components/complex/all-pools-table.tsx
  packages/web/components/complex/paginated-table.tsx
  packages/web/components/complex/pool/create/step3-confirm.tsx
  packages/web/components/complex/transfer.tsx
  packages/web/components/control/checkbox.tsx
  packages/web/components/navbar-osmo-price.tsx
  packages/web/components/table/cells/pool-quick-actions.tsx
  packages/web/components/trade-clipboard/index.tsx
  packages/web/components/trade-clipboard/trade-route.tsx
  packages/web/config/chain-infos.ts
  packages/web/config/utils.ts
  packages/web/hooks/ui-config/use-fake-fee-config.ts
  packages/web/localizations/en.json
  packages/web/localizations/es.json
  packages/web/localizations/fr.json
  packages/web/localizations/ko.json
  packages/web/localizations/pl.json
  packages/web/localizations/pt-br.json
  packages/web/localizations/ro.json
  packages/web/localizations/tr.json
  packages/web/localizations/zh-cn.json
  packages/web/localizations/zh-hk.json
  packages/web/localizations/zh-tw.json
  packages/web/modals/lock-tokens.tsx
  packages/web/package.json
  packages/web/public/icons/sprite.svg
  packages/web/stores/assets/index.ts
  packages/web/stores/assets/types.ts
  packages/web/stores/root.ts
Labels: release
