Repository osmosis-labs/osmosis-frontend, pull requests merged in 2023-08, with the labels that each got.

#1950 Test Unsafe KSM
  packages/web/config/generate-chain-infos/source-chain-infos.ts
  packages/web/config/ibc-assets.ts
  packages/web/config/price.ts
  packages/web/public/tokens/ksm.svg
Labels: pool/asset

#1942 performance: add unsafe IBC currency registrar
  packages/stores/src/currency-registrar/__tests__/mock-data.ts
  packages/stores/src/currency-registrar/__tests__/unsafe-ibc.spec.ts
  packages/stores/src/currency-registrar/index.ts
  packages/stores/src/currency-registrar/lp.ts
  packages/stores/src/currency-registrar/unsafe-ibc.ts
  packages/web/config/generate-chain-infos/source-chain-infos.ts
  packages/web/config/ibc-assets.ts
  packages/web/config/price.ts
  packages/web/public/tokens/ksm.svg
  packages/web/stores/root.ts
Labels: performance 💨

#1936 Web worker router (multi threading)
  .vscode/osmosis-frontend.code-workspace
  packages/pools/src/concentrated/fetch-pool-amount-provider.ts
  packages/pools/src/concentrated/fetch-tick-data-provider.ts
  packages/pools/src/concentrated/index.ts
  packages/pools/src/concentrated/pool.ts
  packages/pools/src/router/routes.ts
  packages/stores/src/currency-registrar/__tests__/mock-data.ts
  packages/stores/src/currency-registrar/__tests__/unsafe-ibc.spec.ts
  packages/stores/src/currency-registrar/index.ts
  packages/stores/src/currency-registrar/lp.ts
  packages/stores/src/currency-registrar/unsafe-ibc.ts
  packages/stores/src/queries/concentrated-liquidity/tick-data-provider.ts
  packages/stores/src/ui-config/trade-token-in-config.ts
  packages/web/components/complex/add-conc-liquidity.tsx
  packages/web/components/control/token-select-with-drawer.tsx
  packages/web/components/swap-tool/index.tsx
  packages/web/components/swap-tool/split-route.tsx
  packages/web/config/generate-chain-infos/source-chain-infos.ts
  packages/web/config/ibc-assets.ts
  packages/web/config/price.ts
  packages/web/config/user-analytics-v2.ts
  packages/web/hooks/index.ts
  packages/web/hooks/ui-config/use-trade-token-in-config.ts
  packages/web/hooks/use-previous-when.ts
  packages/web/localizations/en.json
  packages/web/localizations/es.json
  packages/web/localizations/fa.json
  packages/web/localizations/fr.json
  packages/web/localizations/ko.json
  packages/web/localizations/pl.json
  packages/web/localizations/pt-br.json
  packages/web/localizations/ro.json
  packages/web/localizations/tr.json
  packages/web/localizations/zh-cn.json
  packages/web/localizations/zh-hk.json
  packages/web/localizations/zh-tw.json
  packages/web/modals/trade-tokens.tsx
  packages/web/next.config.js
  packages/web/pages/index.tsx
  packages/web/public/tokens/ksm.svg
  packages/web/stores/root.ts
  packages/web/utils/background-routes/README.md
  packages/web/utils/background-routes/coding/README.md
  packages/web/utils/background-routes/coding/error.ts
  packages/web/utils/background-routes/coding/index.ts
  packages/web/utils/background-routes/coding/out-given-in-router.ts
  packages/web/utils/background-routes/coding/params.ts
  packages/web/utils/background-routes/coding/pool.ts
  packages/web/utils/background-routes/index.ts
  packages/web/utils/background-routes/worker.ts
  packages/web/utils/formatter.ts
  packages/web/utils/string.ts
Labels: performance 💨

#1954 Update Composable Chain Name
  packages/web/config/generate-chain-infos/source-chain-infos.ts
Labels: pool/asset

#1956 Update CUB price
  packages/web/config/price.ts
Labels: pool/asset

#1959 Update BLUE Pricing
  packages/web/config/price.ts
Labels: pool/asset

#1962 Add KYVE token
  packages/web/config/generate-chain-infos/source-chain-infos.ts
  packages/web/config/ibc-assets.ts
  packages/web/public/tokens/kyve.svg
Labels: pool/asset

#1965 Update KYVE Price
  packages/web/config/generate-chain-infos/source-chain-infos.ts
  packages/web/config/price.ts
Labels: pool/asset

#1810 Add ampOSMO
  packages/web/config/generate-chain-infos/source-chain-infos.ts
  packages/web/config/price.ts
  packages/web/public/tokens/amp.osmo.png
Labels: pool/asset

#1940 Update PLQ Deposit URL
  packages/web/config/ibc-assets.ts
Labels: pool/asset

#1991 Fix Tailwind theme: remove overloaded theme config
  packages/web/components/funnels/concentrated-liquidity/intro.tsx
  packages/web/components/pool-detail/concentrated.tsx
  packages/web/components/swap-tool/split-route.tsx
  packages/web/components/table/cells/pool-composition.tsx
  packages/web/tailwind.config.js
Labels: bug

#1985 Fall back to pre v17 queries
  packages/stores/src/queries/pools/cfmm-cl-link.ts
  packages/stores/src/queries/store.ts
  packages/stores/src/queries/tendermint/node-info.ts
Labels: bug

#1992 Publish stage
  .github/workflows/lint-and-check-format.yml
  .gitignore
  .vscode/settings.json
  packages/stores/src/currency-registrar/__tests__/unsafe-ibc.spec.ts
  packages/stores/src/currency-registrar/unsafe-ibc.ts
  packages/stores/src/queries-external/token-pair-historical-chart/index.ts
  packages/stores/src/queries/concentrated-liquidity/cl-to-cfmm-link.ts
  packages/stores/src/queries/concentrated-liquidity/index.ts
  packages/stores/src/queries/pools/cfmm-cl-link.ts
  packages/stores/src/queries/pools/cfmm-to-cl-link.ts
  packages/stores/src/queries/pools/index.ts
  packages/stores/src/queries/pools/types.ts
  packages/stores/src/queries/store.ts
  packages/stores/src/queries/tendermint/node-info.ts
  packages/stores/src/ui-config/user-upgrades.ts
  packages/web/components/funnels/concentrated-liquidity/intro.tsx
  packages/web/components/pool-detail/concentrated.tsx
  packages/web/components/swap-tool/split-route.tsx
  packages/web/components/table/cells/pool-composition.tsx
  packages/web/config/ads-banner.json
  packages/web/config/generate-chain-infos/source-chain-infos.ts
  packages/web/config/ibc-assets.ts
  packages/web/config/price.ts
  packages/web/config/user-analytics-v2.ts
  packages/web/hooks/ui-config/use-historical-and-depth-data.ts
  packages/web/modals/validator-next-step.tsx
  packages/web/modals/validator-squad.tsx
  packages/web/pages/index.tsx
  packages/web/pages/stake/index.tsx
  packages/web/public/tokens/dot.comp.svg
  packages/web/public/tokens/usdt.axl.svg
  packages/web/public/tokens/usdt.grv.svg
  packages/web/stores/derived-data/concentrated-liquidity/historical-and-liquidity-data.ts
  packages/web/tailwind.config.js
Labels: release

#1994 Token Listing: Testnet XPRT
  packages/web/config/generate-chain-infos/source-chain-infos.ts
  packages/web/config/ibc-assets.ts
Labels: pool/asset

#2006 fix(teritori): update logo
  packages/web/public/tokens/utori.svg
Labels: pool/asset

#2008 Asset Integrations: Verify HASH, DARC, NTRN
  packages/web/config/ibc-assets.ts
Labels: pool/asset

#2017 Asset Integrations: Fix SEI Withdraw link
  packages/web/config/ibc-assets.ts
Labels: pool/asset

#2016 Asset Integration: Add SEI (to master)
  packages/web/config/generate-chain-infos/__tests__/utils.spec.ts
  packages/web/config/generate-chain-infos/source-chain-infos.ts
  packages/web/config/ibc-assets.ts
  packages/web/public/tokens/sei.svg
Labels: pool/asset

#2021 Enable Chihuahua deposit/withdraw
  packages/web/config/ibc-assets.ts
Labels: pool/asset

#2022 Asset Integrations: Update SEI Price
  packages/web/config/generate-chain-infos/source-chain-infos.ts
  packages/web/config/price.ts
Labels: pool/asset

#2028 Asset Integrations: Add qSOMM
  packages/web/config/generate-chain-infos/source-chain-infos.ts
  packages/web/config/ibc-assets.ts
  packages/web/config/price.ts
  packages/web/public/tokens/qsomm.svg
Labels: pool/asset

#2011 Update Stride Token Logo
  packages/web/config/generate-chain-infos/source-chain-infos.ts
  packages/web/public/tokens/stride.svg
Labels: pool/asset

#2029 Asset Integrations: Add kava.USDT
  packages/web/config/generate-chain-infos/source-chain-infos.ts
  packages/web/config/ibc-assets.ts
  packages/web/config/price.ts
Labels: pool/asset

#2051 chore: Change TORI Image Name
  packages/web/config/generate-chain-infos/source-chain-infos.ts
  packages/web/public/tokens/tori.svg
Labels: pool/asset

#2059 Asset Integrations: KYVE Verified
  packages/web/config/ibc-assets.ts
Labels: pool/asset

#2062 Asset Integrations: LUMEN Unstable
  packages/web/config/ibc-assets.ts
Labels: pool/asset

#2063 fix: fix CL intro modal
  packages/web/localizations/en.json
  packages/web/localizations/es.json
  packages/web/localizations/fa.json
  packages/web/localizations/fr.json
  packages/web/localizations/ko.json
  packages/web/localizations/pl.json
  packages/web/localizations/pt-br.json
  packages/web/localizations/ro.json
  packages/web/localizations/tr.json
  packages/web/localizations/zh-cn.json
  packages/web/localizations/zh-hk.json
  packages/web/localizations/zh-tw.json
Labels: bug
