Repository osmosis-labs/osmosis-frontend, pull requests merged in 2023-01, with the labels that each got.

#1187 Hotfix
  packages/stores/src/queries/lockup/account-locked.ts
  packages/web/config/chain-infos.ts
  packages/web/config/price.ts
  packages/web/hooks/window/use-token-swap-query-params.ts
  packages/web/pages/pool/[id].tsx
Labels: bug

#1190 Optimized gauge query + add derived data stores
  packages/stores/README.md
  packages/stores/src/derived-data/index.ts
  packages/stores/src/derived-data/pool/bonding.ts
  packages/stores/src/derived-data/pool/details.ts
  packages/stores/src/derived-data/pool/index.ts
  packages/stores/src/derived-data/pool/superfluid.ts
  packages/stores/src/derived-data/pool/types.ts
  packages/stores/src/derived-data/store.ts
  packages/stores/src/index.ts
  packages/stores/src/queries-external/active-gauges/index.ts
  packages/stores/src/queries-external/active-gauges/types.ts
  packages/stores/src/queries-external/index.ts
  packages/stores/src/queries-external/store.ts
  packages/stores/src/queries/incentives/gauge-by-id.ts
  packages/stores/src/queries/incentives/types.ts
  packages/stores/src/queries/pool-incentives/incentivized-pools.ts
  packages/stores/src/queries/pool-incentives/pool-gauges.ts
  packages/stores/src/queries/pools/index.ts
  packages/stores/src/queries/pools/types.ts
  packages/stores/src/queries/store.ts
  packages/stores/src/queries/superfluid-pools/index.ts
  packages/stores/src/ui-config/index.ts
  packages/stores/src/ui-config/manage-liquidity/bond-liquidity.ts
  packages/stores/src/ui-config/manage-liquidity/index.ts
  packages/stores/src/ui-config/user-config.ts
  packages/stores/types/queries-external/ibc/index.d.ts
  packages/stores/types/queries-external/ibc/status-by-id.d.ts
  packages/stores/types/queries-external/ibc/types.d.ts
  packages/stores/types/queries/ibc/index.d.ts
  packages/stores/types/queries/ibc/status-by-id.d.ts
  packages/stores/types/queries/ibc/types.d.ts
  packages/web/components/complex/external-incentivized-pools-table-set.tsx
  packages/web/config/feature-flag.ts
  packages/web/hooks/ui-config/index.ts
  packages/web/hooks/ui-config/use-bond-liquidity-config.ts
  packages/web/hooks/ui-config/use-pool-detail-config.ts
  packages/web/hooks/ui-config/use-pool-gauges.ts
  packages/web/hooks/ui-config/use-superfluid-pool-config.ts
  packages/web/hooks/ui-config/use-superfluid-pool.ts
  packages/web/modals/lock-tokens.tsx
  packages/web/pages/api/active-gauges.ts
  packages/web/pages/assets/index.tsx
  packages/web/pages/pool/[id].tsx
  packages/web/pages/pools/index.tsx
  packages/web/stores/root.ts
Labels: developer-qol 💻, refactor

#1213 Add DYS
  packages/web/config/chain-infos.ts
  packages/web/config/ibc-assets.ts
  packages/web/config/price.ts
  packages/web/public/tokens/dys.svg
Labels: pool/asset

#1230 add arUSD from Acrechain
  packages/web/config/chain-infos.ts
  packages/web/config/ibc-assets.ts
  packages/web/config/price.ts
  packages/web/public/tokens/arusd.png
Labels: pool/asset

#1233 Lower 'w' in WAVAX to wAVAX
  packages/web/config/chain-infos.ts
Labels: pool/asset

#1234 Make wAVAX.axl logo red (like AVAX)
  packages/web/config/chain-infos.ts
  packages/web/public/tokens/avax.svg
Labels: pool/asset

#1206 Update Axelar testnet network and channels
  packages/web/config/chain-infos.ts
  packages/web/config/ibc-assets.ts
  packages/web/integrations/axelar/transfer.tsx
Labels: pool/asset

#1251 Add CANTO
  packages/web/config/chain-infos.ts
  packages/web/config/ibc-assets.ts
  packages/web/config/price.ts
  packages/web/public/tokens/canto.png
Labels: pool/asset

#1257 Update Canto fee
  packages/web/config/chain-infos.ts
Labels: pool/asset

#1265 fix canto gas prices
  packages/web/config/chain-infos.ts
Labels: pool/asset

#1267 Reorder Assets
  packages/stores/src/derived-data/pool/bonding.ts
  packages/stores/src/queries-external/filtered-pools/filtered-pools.ts
  packages/stores/src/queries-external/filtered-pools/utils.ts
  packages/web/components/alert/tx-event-toast.ts
  packages/web/components/control/token-select-with-drawer.tsx
  packages/web/components/trade-clipboard/index.tsx
  packages/web/config/chain-infos.ts
  packages/web/config/ibc-assets.ts
  packages/web/config/price.ts
  packages/web/integrations/axelar/source-chain-config.ts
  packages/web/integrations/axelar/transfer.tsx
  packages/web/localizations/en.json
  packages/web/pages/api/active-gauges.ts
  packages/web/pages/index.tsx
  packages/web/public/tokens/canto.png
  packages/web/public/tokens/ftm.png
Labels: pool/asset

#1282 update DYS OSMO pool
  packages/web/config/price.ts
Labels: pool/asset

#1277 Add qSTARS
  packages/web/config/chain-infos.ts
  packages/web/config/ibc-assets.ts
  packages/web/config/price.ts
  packages/web/public/tokens/qstars.svg
Labels: pool/asset

#1275 Add HOPERS price
  packages/web/config/chain-infos.ts
  packages/web/config/price.ts
Labels: pool/asset

#1278 Add WYND
  packages/web/config/chain-infos.ts
  packages/web/config/ibc-assets.ts
  packages/web/config/price.ts
  packages/web/public/tokens/wynd.svg
Labels: pool/asset
